apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: hh4fxhzdx-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hh4fxhzdx-go 
  name: hh4fxhzdx-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: hh4fxhzdx-go 
